using Microsoft.Extensions.Logging;
using POM.Auth.Ports;

namespace POM.Sms;

/// <summary>
/// Dev/test-only <see cref="ISmsSender"/>: writes the message (including the OTP code) to a structured
/// log instead of sending a real SMS. There is <b>no</b> fixed/constant OTP — the code is always
/// framework-generated by <c>IOtpSender</c> and surfaced here only so local/automated flows can read
/// it (plan 0004 Q5). Production must be configured with the real provider (task 0017) so logs never
/// carry a code. Selected when <c>Sms:Provider</c> is <c>"Logging"</c> (the default).
/// </summary>
public sealed class LoggingSmsSender : ISmsSender
{
    private readonly ILogger<LoggingSmsSender> _logger;

    public LoggingSmsSender(ILogger<LoggingSmsSender> logger) => _logger = logger;

    public Task SendAsync(string phoneNumber, string message, CancellationToken ct)
    {
        _logger.LogInformation("SMS (dev LoggingSmsSender) -> {PhoneNumber}: {Message}", phoneNumber, message);
        return Task.CompletedTask;
    }
}
